#FROM node:18.4.0-alpine3.16
FROM node:20.13.1

WORKDIR /app

COPY package*.json ./

COPY public ./public
COPY src ./src
COPY .env ./.env
COPY .eslintrc.cjs ./.eslintrc.cjs
COPY index.html ./index.html
COPY tsconfig.json ./tsconfig.json
COPY tsconfig.node.json ./tsconfig.node.json
COPY vite.config.ts ./vite.config.ts

RUN npm install

RUN npm run build

RUN npm install -g serve
